import Balance from "./components/Balance";
import ButtonEx from "./components/ButtonEx";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import { ChartUp } from "./constants/images";
import Image from "next/image";


export const metadata = {
  title: "User Panel",
  description: "Generated by create next app",
};

export default function PanelLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <section className="main-holder">
          <div className="container-fluid">
            <div className="row">
              <div className="col-2 side-menu-background">
                <Sidebar />
              </div>
              <div className="col-12 col-lg-10">
                <div className="right-holder-content">
                  <div className="banner-header">
                    <div className="row">
                      <div className="col-6">
                        <Balance />
                      </div>
                      <div className="col-6">
                        <div className="banner-header-1">
                          <ButtonEx />
                          <div className="">
                            <Image
                              src={ChartUp}
                              alt="Increase"
                              width={199}
                              height={110}
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {children}
                </div>
                <Footer />
              </div>
            </div>
          </div>
        </section>
       
      </body>
    </html>
  );
}
