
import "bootstrap/dist/css/bootstrap.min.css";

import "./globals.css";

import Script from "next/script";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}

        <Script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></Script>
        <Script src="/js/openactive.js"></Script>
        <Script src="/js/sidenav.js"></Script>
      </body>
    </html>
  );
}
